#!/usr/bin/env python3
import time
t0 = time.time()

from selenium import webdriver as wd
import sys, time, re, json, subprocess
from urllib.request import urlopen
from tempfile import gettempdir
from getpass import getuser
from os import path


WD_HOST = 'localhost'
WD_PORT = 8910
WD_URL  = 'http://%s:%d/status' %(WD_HOST, WD_PORT)

def try_phantom():
    try:
        resp = urlopen(WD_URL, timeout=0.010)
        assert resp.code == 200
        assert re.match(r'application/json\b', resp.headers['content-type'])
        answer = json.loads(resp.read().decode())
        for k in ['sessionId', 'status']:
            assert k in answer.keys()
        return True
    except:
        return None

if not try_phantom():
    phantom_logfile = path.join(gettempdir(), 'phantomjs-%s.log' % getuser())
    subprocess.Popen('phantomjs --wd', shell=True,
                     stdout=subprocess.DEVNULL,
                     stderr=open(phantom_logfile,'a'))
    interval = 0.010
    i, maxtry = 0, 1/interval
    while True:
        time.sleep(interval)
        if try_phantom(): break
        i += 1
        if i >= maxtry:
            raise SystemExit(
                "%s: phantomjs at %s:%d not detected after %d tries"
                "\n\tcheck %s for possible details"
                %(sys.argv[0], WD_HOST, WD_PORT, i, phantom_logfile))
    
d = wd.PhantomJS(port=WD_PORT)

sentence = ' '.join(sys.argv[1:])

d.get('http://translate.google.pl/#en/pl')
d.find_element_by_id('gt-otf-switch').click()
s = d.find_element_by_id('source')
r = d.find_element_by_id('result_box')
c = d.find_element_by_id('gt-submit')
s.clear()
s.send_keys(sentence)
c.click()

interval = 0.100
while not r.text:
    time.sleep(interval)
    interval = max(interval*0.95, 0.010)

t1 = time.time()

print('[%.2fs] '%(t1-t0+0.050), r.text)
